spring:
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  r2dbc:
    url: r2dbc:pool:postgres://localhost:5432/person
    username: postgres
    password: postgres
  flyway:
    url: jdbc:postgresql://localhost:5432/person
    user: postgres
    password: postgres


server:
  port: 8084

logging:
  level:
    org:
      springframework:
        security: DEBUG