spring:
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  r2dbc:
    url: r2dbc:pool:postgres://localhost:5432/person
    username: postgres
    password: postgres
  flyway:
    url: jdbc:postgresql://localhost:5432/person
    user: postgres
    password: postgres

notification:
  kafka:
    host: "localhost:9093"

integration:
  notification-property:
    base-url: ${NOTIFICATION_URL}
    update-status: "update"
    users-notification: ""

server:
  port: 8082

logging:
  level:
    org:
      springframework:
        security: DEBUG