spring:
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  r2dbc:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  flyway:
    url: ${FLYWAY_DATASOURCE_URL}
    user: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

notification:
  kafka:
    host: ${KAFKA_HOST}

integration:
  notification-property:
    base-url: ${NOTIFICATION_URL}
    update-status: "update"
    users-notification: ""

logging:
  level:
    org:
      springframework:
        security: DEBUG